version: "3.4"
services:

  mongo:
    image: mongo:3.6
    ports:
      - "27017:27017"

  elasticsearch:
    image: elasticsearch:7.1.0
    environment:
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
